Proyecto WEB/Prj_ConAud/config/routes.rb
Rails.application.routes.draw do
  resources :denuncias
  resources :tip_docs
  resources :seguimientos
  resources :estados
  resources :denuncia
  resources :denunciantes
  resources :autoridads
  devise_for :users
  resources :home

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
   
namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post '/authentication_tokens/create', to: "authentication_tokens#create"
      end
    end
  end
end

Proyecto WEB/Prj_ConAud/app/models/autoridad.rb
class Autoridad < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/controllers/autoridads_controller.rb
class AutoridadsController < ApplicationController
  before_action :set_autoridad, only: [:show, :edit, :update, :destroy]

  # GET /autoridad
  # GET /autoridad.json
  def index
    @autoridads = Autoridad.all  
  end

  # GET /autoridads/1
  # GET /autoridads/1.json
  def show
  end

  # GET /autoridads/new
  def new
    @autoridad = Autoridad.new
  end

  # GET /autoridads/1/edit
  def edit
  end

  # POST /autoridads
  # POST /autoridads.json
  def create
    @autoridad = Autoridad.new(autoridad_params)

    respond_to do |format|
      if @autoridad.save
        format.html { redirect_to @autoridad, notice: 'Autoridad was successfully created.' }
        format.json { render :show, status: :created, location: @autoridad }
      else
        format.html { render :new }
        format.json { render json: @autoridad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autoridads/1
  # PATCH/PUT /autoridads/1.json
  def update
    respond_to do |format|
      if @autoridad.update(autoridad_params)
        format.html { redirect_to @autoridad, notice: 'Autoridad was successfully updated.' }
        format.json { render :show, status: :ok, location: @autoridad }
      else
        format.html { render :edit }
        format.json { render json: @autoridad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autoridads/1
  # DELETE /autoridads/1.json
  def destroy
    @autoridad.destroy
    respond_to do |format|
      format.html { redirect_to autoridads_url, notice: 'Autoridad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autoridad
      @autoridad = Autoridad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autoridad_params
      params.require(:autoridad).permit(:id_aut, :id_tip_doc, :num_doc_aut, :pri_nom_aut, :seg_nom_aut, :pri_ape_aut, :seg_ape_aut, :usu_aut, :pas_aut)
    end
end

Proyecto WEB/Prj_ConAud/app/helpers/autoridads_helper.rb
module AutoridadsHelper
end

Proyecto WEB/Prj_ConAud/app/views/autoridads/_form.html.erb
<%= form_with(model: autoridad, local: true) do |form| %>
  <% if autoridad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(autoridad.errors.count, "error") %> prohibited this autoridad from being saved:</h2>

      <ul>
      <% autoridad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_aut %>
    <%= form.text_field :id_aut %>
  </div>

  <div class="field">
    <%= form.label :id_tip_doc %>
    <%= form.number_field :id_tip_doc %>
  </div>

  <div class="field">
    <%= form.label :num_doc_aut %>
    <%= form.number_field :num_doc_aut %>
  </div>

  <div class="field">
    <%= form.label :pri_nom_aut %>
    <%= form.text_field :pri_nom_aut %>
  </div>

  <div class="field">
    <%= form.label :seg_nom_aut %>
    <%= form.text_field :seg_nom_aut %>
  </div>

  <div class="field">
    <%= form.label :pri_ape_aut %>
    <%= form.text_field :pri_ape_aut %>
  </div>

  <div class="field">
    <%= form.label :seg_ape_aut %>
    <%= form.text_field :seg_ape_aut %>
  </div>

  <div class="field">
    <%= form.label :usu_aut %>
    <%= form.text_field :usu_aut %>
  </div>

  <div class="field">
    <%= form.label :pas_aut %>
    <%= form.text_field :pas_aut %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Proyecto WEB/Prj_ConAud/app/views/autoridads/edit.html.erb
<h1>Editing Autoridad</h1>

<%= render 'form', autoridad: @autoridad %>

<%= link_to 'Show', @autoridad %> |
<%= link_to 'Back', autoridads_path %>

Proyecto WEB/Prj_ConAud/app/views/autoridads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autoridads</h1>

<table>
  <thead>
    <tr>
      <th>Id aut</th>
      <th>Id tip doc</th>
      <th>Num doc aut</th>
      <th>Pri nom aut</th>
      <th>Seg nom aut</th>
      <th>Pri ape aut</th>
      <th>Seg ape aut</th>
      <th>Usu aut</th>
      <th>Pas aut</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autoridads.each do |autoridad| %>
      <tr>
        <td><%= autoridad.id_aut %></td>
        <td><%= autoridad.id_tip_doc %></td>
        <td><%= autoridad.num_doc_aut %></td>
        <td><%= autoridad.pri_nom_aut %></td>
        <td><%= autoridad.seg_nom_aut %></td>
        <td><%= autoridad.pri_ape_aut %></td>
        <td><%= autoridad.seg_ape_aut %></td>
        <td><%= autoridad.usu_aut %></td>
        <td><%= autoridad.pas_aut %></td>
        <td><%= link_to 'Show', autoridad %></td>
        <td><%= link_to 'Edit', edit_autoridad_path(autoridad) %></td>
        <td><%= link_to 'Destroy', autoridad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Autoridad', new_autoridad_path %>

Proyecto WEB/Prj_ConAud/app/views/autoridads/new.html.erb
<h1>New Autoridad</h1>

<%= render 'form', autoridad: @autoridad %>

<%= link_to 'Back', autoridads_path %>

Proyecto WEB/Prj_ConAud/app/views/autoridads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id aut:</strong>
  <%= @autoridad.id_aut %>
</p>

<p>
  <strong>Id tip doc:</strong>
  <%= @autoridad.id_tip_doc %>
</p>

<p>
  <strong>Num doc aut:</strong>
  <%= @autoridad.num_doc_aut %>
</p>

<p>
  <strong>Pri nom aut:</strong>
  <%= @autoridad.pri_nom_aut %>
</p>

<p>
  <strong>Seg nom aut:</strong>
  <%= @autoridad.seg_nom_aut %>
</p>

<p>
  <strong>Pri ape aut:</strong>
  <%= @autoridad.pri_ape_aut %>
</p>

<p>
  <strong>Seg ape aut:</strong>
  <%= @autoridad.seg_ape_aut %>
</p>

<p>
  <strong>Usu aut:</strong>
  <%= @autoridad.usu_aut %>
</p>

<p>
  <strong>Pas aut:</strong>
  <%= @autoridad.pas_aut %>
</p>

<%= link_to 'Edit', edit_autoridad_path(@autoridad) %> |
<%= link_to 'Back', autoridads_path %>