Proyecto WEB/Prj_ConAud/config/routes.rb
Rails.application.routes.draw do
  resources :denuncias
  resources :tip_docs
  resources :seguimientos
  resources :estados
  resources :denuncia
  resources :denunciantes
  resources :autoridads
  devise_for :users
  resources :home

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
   
namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post '/authentication_tokens/create', to: "authentication_tokens#create"
      end
    end
  end
end

Proyecto WEB/Prj_ConAud/app/models/denuncia.rb
class Denuncia < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/denuncias.rb
class Denuncias < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/controllers/denuncia_controller.rb
class DenunciaController < ApplicationController
  before_action :set_denuncium, only: [:show, :edit, :update, :destroy]

  # GET /denuncia
  # GET /denuncia.json
  def index
    @denuncia = Denuncium.all
  end

  # GET /denuncia/1
  # GET /denuncia/1.json
  def show
  end

  # GET /denuncia/new
  def new
    @denuncium = Denuncium.new
  end

  # GET /denuncia/1/edit
  def edit
  end

  # POST /denuncia
  # POST /denuncia.json
  def create
    @denuncium = Denuncium.new(denuncium_params)

    respond_to do |format|
      if @denuncium.save
        format.html { redirect_to @denuncium, notice: 'Denuncium was successfully created.' }
        format.json { render :show, status: :created, location: @denuncium }
      else
        format.html { render :new }
        format.json { render json: @denuncium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /denuncia/1
  # PATCH/PUT /denuncia/1.json
  def update
    respond_to do |format|
      if @denuncium.update(denuncium_params)
        format.html { redirect_to @denuncium, notice: 'Denuncium was successfully updated.' }
        format.json { render :show, status: :ok, location: @denuncium }
      else
        format.html { render :edit }
        format.json { render json: @denuncium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denuncia/1
  # DELETE /denuncia/1.json
  def destroy
    @denuncium.destroy
    respond_to do |format|
      format.html { redirect_to denuncia_url, notice: 'Denuncium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_denuncium
      @denuncium = Denuncium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def denuncium_params
      params.require(:denuncium).permit(:id_den, :id_usu_den, :lat_den, :lon_den, :ima_fue, :aud_rep, :aud_niv, :fec_den, :hor_den)
    end
end

Proyecto WEB/Prj_ConAud/app/controllers/denuncias_controller.rb
class DenunciasController < ApplicationController
  before_action :set_denuncia, only: [:show, :edit, :update, :destroy]

  # GET /denuncias
  # GET /denuncias.json
  def index
    @denuncias = Denuncias.all
  end

  # GET /denuncias/1
  # GET /denuncias/1.json
  def show
  end

  # GET /denuncias/new
  def new
    @denuncia = Denuncias.new
  end

  # GET /denuncias/1/edit
  def edit
  end

  # POST /denuncias
  # POST /denuncias.json
  def create
    @denuncia = Denuncias.new(denuncia_params)

    respond_to do |format|
      if @denuncia.save
        format.html { redirect_to @denuncia, notice: 'Denuncias was successfully created.' }
        format.json { render :show, status: :created, location: @denuncia }
      else
        format.html { render :new }
        format.json { render json: @denuncia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /denuncias/1
  # PATCH/PUT /denuncias/1.json
  def update
    respond_to do |format|
      if @denuncia.update(denuncia_params)
        format.html { redirect_to @denuncia, notice: 'Denuncias was successfully updated.' }
        format.json { render :show, status: :ok, location: @denuncia }
      else
        format.html { render :edit }
        format.json { render json: @denuncia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denuncias/1
  # DELETE /denuncias/1.json
  def destroy
    @denuncia.destroy
    respond_to do |format|
      format.html { redirect_to denuncias_index_url, notice: 'Denuncias was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_denuncia
      @denuncia = Denuncias.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def denuncia_params
      params.require(:denuncia).permit(:id_den, :id_usu_den, :lat_den, :lon_den, :ima_fue, :aud_rep, :aud_niv, :fec_den, :hor_den)
    end
end

Proyecto WEB/Prj_ConAud/app/helpers/denuncia_helper.rb
module DenunciaHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/denuncias_helper.rb
module DenunciasHelper
end

Proyecto WEB/Prj_ConAud/app/views/denuncias/_form.html.erb
<%= form_with(model: denuncia, local: true) do |form| %>
  <% if denuncia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(denuncia.errors.count, "error") %> prohibited this denuncia from being saved:</h2>

      <ul>
      <% denuncia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_den %>
    <%= form.text_field :id_den %>
  </div>

  <div class="field">
    <%= form.label :id_usu_den %>
    <%= form.number_field :id_usu_den %>
  </div>

  <div class="field">
    <%= form.label :lat_den %>
    <%= form.text_field :lat_den %>
  </div>

  <div class="field">
    <%= form.label :lon_den %>
    <%= form.text_field :lon_den %>
  </div>

  <div class="field">
    <%= form.label :ima_fue %>
    <%= form.text_field :ima_fue %>
  </div>

  <div class="field">
    <%= form.label :aud_rep %>
    <%= form.text_field :aud_rep %>
  </div>

  <div class="field">
    <%= form.label :aud_niv %>
    <%= form.text_field :aud_niv %>
  </div>

  <div class="field">
    <%= form.label :fec_den %>
    <%= form.date_select :fec_den %>
  </div>

  <div class="field">
    <%= form.label :hor_den %>
    <%= form.time_select :hor_den %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Proyecto WEB/Prj_ConAud/app/views/denuncias/edit.html.erb
<h1>Editing Denuncia</h1>

<%= render 'form', denuncia: @denuncia %>

<%= link_to 'Show', @denuncia %> |
<%= link_to 'Back', denuncias_index_path %>

Proyecto WEB/Prj_ConAud/app/views/denuncias/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Denuncias</h1>

<table>
  <thead>
    <tr>
      <th>Id den</th>
      <th>Id usu den</th>
      <th>Lat den</th>
      <th>Lon den</th>
      <th>Ima fue</th>
      <th>Aud rep</th>
      <th>Aud niv</th>
      <th>Fec den</th>
      <th>Hor den</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @denuncias.each do |denuncia| %>
      <tr>
        <td><%= denuncia.id_den %></td>
        <td><%= denuncia.id_usu_den %></td>
        <td><%= denuncia.lat_den %></td>
        <td><%= denuncia.lon_den %></td>
        <td><%= denuncia.ima_fue %></td>
        <td><%= denuncia.aud_rep %></td>
        <td><%= denuncia.aud_niv %></td>
        <td><%= denuncia.fec_den %></td>
        <td><%= denuncia.hor_den %></td>
        <td><%= link_to 'Show', denuncia %></td>
        <td><%= link_to 'Edit', edit_denuncia_path(denuncia) %></td>
        <td><%= link_to 'Destroy', denuncia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Denuncia', new_denuncia_path %>

Proyecto WEB/Prj_ConAud/app/views/denuncias/new.html.erb
<h1>New Denuncia</h1>

<%= render 'form', denuncia: @denuncia %>

<%= link_to 'Back', denuncias_index_path %>

Proyecto WEB/Prj_ConAud/app/views/denuncias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id den:</strong>
  <%= @denuncia.id_den %>
</p>

<p>
  <strong>Id usu den:</strong>
  <%= @denuncia.id_usu_den %>
</p>

<p>
  <strong>Lat den:</strong>
  <%= @denuncia.lat_den %>
</p>

<p>
  <strong>Lon den:</strong>
  <%= @denuncia.lon_den %>
</p>

<p>
  <strong>Ima fue:</strong>
  <%= @denuncia.ima_fue %>
</p>

<p>
  <strong>Aud rep:</strong>
  <%= @denuncia.aud_rep %>
</p>

<p>
  <strong>Aud niv:</strong>
  <%= @denuncia.aud_niv %>
</p>

<p>
  <strong>Fec den:</strong>
  <%= @denuncia.fec_den %>
</p>

<p>
  <strong>Hor den:</strong>
  <%= @denuncia.hor_den %>
</p>

<%= link_to 'Edit', edit_denuncia_path(@denuncia) %> |
<%= link_to 'Back', denuncias_index_path %>