Proyecto WEB/Prj_ConAud/config/routes.rb
Rails.application.routes.draw do
  resources :denuncias
  resources :tip_docs
  resources :seguimientos
  resources :estados
  resources :denuncia
  resources :denunciantes
  resources :autoridads
  devise_for :users
  resources :home

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
   
namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post '/authentication_tokens/create', to: "authentication_tokens#create"
      end
    end
  end
end

Proyecto WEB/Prj_ConAud/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Proyecto WEB/Prj_ConAud/app/models/autoridad.rb
class Autoridad < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/denuncia.rb
class Denuncia < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/denunciante.rb
class Denunciante < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/denuncias.rb
class Denuncias < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/estado.rb
class Estado < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/seguimiento.rb
class Seguimiento < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/tip_doc.rb
class TipDoc < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: Devise::JWT::RevocationStrategies::Null

end

Proyecto WEB/Prj_ConAud/app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:id_est_den, :nom_est)
    end
end

Proyecto WEB/Prj_ConAud/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home		
	end
	def index
    
    end
	 def show
     end

end

Proyecto WEB/Prj_ConAud/app/helpers/application_helper.rb
module ApplicationHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/autoridads_helper.rb
module AutoridadsHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/denuncia_helper.rb
module DenunciaHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/denunciantes_helper.rb
module DenunciantesHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/denuncias_helper.rb
module DenunciasHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/estados_helper.rb
module EstadosHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/home_helper.rb
module HomeHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/seguimientos_helper.rb
module SeguimientosHelper
end

Proyecto WEB/Prj_ConAud/app/helpers/tip_docs_helper.rb
module TipDocsHelper
end

Proyecto WEB/Prj_ConAud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrjConaud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.49.0/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.49.0/mapbox-gl.css' rel='stylesheet' />

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">CONAUD</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Formularios
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%=seguimientos_path%>">Seguimientos</a>
          <a class="dropdown-item" href="<%=denuncias_path%>">Denuncias</a>
          <a class="dropdown-item" href="<%=denunciantes_path%>">Denunciantes</a>
          <a class="dropdown-item" href="<%=autoridads_path%>">Autoridades</a>  
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%=estados_path%>">Estados</a>
          <a class="dropdown-item" href="<%=tip_docs_path%>">Tipo Documentos</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item">
                
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <a class="nav-link" href="<%= new_user_session_path%>">Login</a>
    </form>

    
  </div>
  
</nav>
    <% flash.each do |key, value| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Alerta!</strong> <%= value %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  
</div>
<% end %>
<!-- 
<%= link_to 'Login', new_user_session_path %>
<%= link_to 'Home', ''%>

 -->    
  <%= yield %>
  </body>
</html>