Proyecto WEB/Prj_ConAud/config/routes.rb
Rails.application.routes.draw do
  resources :denuncias
  resources :tip_docs
  resources :seguimientos
  resources :estados
  resources :denuncia
  resources :denunciantes
  resources :autoridads
  devise_for :users
  resources :home

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'
   
namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post '/authentication_tokens/create', to: "authentication_tokens#create"
      end
    end
  end
end

Proyecto WEB/Prj_ConAud/app/models/estado.rb
class Estado < ApplicationRecord
end

Proyecto WEB/Prj_ConAud/app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:id_est_den, :nom_est)
    end
end

Proyecto WEB/Prj_ConAud/app/helpers/estados_helper.rb
module EstadosHelper
end

Proyecto WEB/Prj_ConAud/app/views/estados/_form.html.erb
<%= form_with(model: estado, local: true) do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_est_den %>
    <%= form.text_field :id_est_den %>
  </div>

  <div class="field">
    <%= form.label :nom_est %>
    <%= form.text_field :nom_est %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Proyecto WEB/Prj_ConAud/app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

Proyecto WEB/Prj_ConAud/app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table>
  <thead>
    <tr>
      <th>Id est den</th>
      <th>Nom est</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.id_est_den %></td>
        <td><%= estado.nom_est %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

Proyecto WEB/Prj_ConAud/app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

Proyecto WEB/Prj_ConAud/app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id est den:</strong>
  <%= @estado.id_est_den %>
</p>

<p>
  <strong>Nom est:</strong>
  <%= @estado.nom_est %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>